In [ ]:
import os
os.kill(os.getpid(), 9)

: 

: 

: 

In [2]:
!git clone https://github.com/LeoQUENETTE/Projet-ML2.git
%ls
%cd Projet-ML2/
!git checkout clip
%pwd
!git branch -a
!git pull

Cloning into 'Projet-ML2'...
remote: Enumerating objects: 1454, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 1454 (delta 3), reused 12 (delta 1), pack-reused 1439 (from 1)
Receiving objects: 100% (1454/1454), 87.62 MiB | 50.10 MiB/s, done.
Resolving deltas: 100% (118/118), done.
Projet-ML2/  sample_data/
/content/Projet-ML2
Branch 'clip' set up to track remote branch 'clip' from 'origin'.
Switched to a new branch 'clip'
* clip
  main
  remotes/origin/HEAD -> origin/main
  remotes/origin/clip
  remotes/origin/images
  remotes/origin/main
  remotes/origin/textes
Already up to date.


## Importation des fichiers

In [3]:
!pip install -r requirements.txt #Si les imports ne sont pas présents

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 118.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 102.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 620.7/620.7 MB 3.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 77.7 MB/s eta 0:00:00:00:0100:01
  Attempting uninstall: Requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.19.0
    Uninstalling tensorboard-2.19.0:
      Successfully uninstalled tensorboard-2.19.0

In [4]:
import sys
import os
sys.path.insert(0, os.path.abspath('./src'))
sys.path.insert(0, os.path.abspath('./src/functions'))
sys.path.insert(0, os.path.abspath('./src/classes'))
%cd src

/content/Projet-ML2/src


## Partie code

In [5]:
from Config import *
from create_X_Y import *
from download_data_from_poncelet import *

df = download_data_from_poncelet()
config = Config()
X, y = create_x_y(config.sequence_lenght, df)
print(X)
print(y)

Données déjà disponibles dans : flickr_subset2
[[ 2 10  5 ...  0  0  0]
 [ 2 11  1 ...  0  0  0]
 [ 2 10  6 ...  0  0  0]
 ...
 [ 2  1  8 ...  0  0  0]
 [ 2  1  7 ...  0  0  0]
 [ 2 11  3 ...  0  0  0]]
['dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 

In [5]:
from functions.create_X_Y import test
test() 

test
